aruna/api/storage/models/v1/auth.proto

This is a small feature that introduces the displayname of an user to the project permissions.
It enables users to see a specific "username" for their projects instead of the anonymous user uuid.
Internally the user-id is still the only source of truth and this will not change since every user can change its displayname
at any time and these names are NOT unique.
Please don´t write any code that relies on display_names.

Feature: Displayname for ProjectPermissions

---

aruna/api/storage/models/v1/auth.proto
aruna/api/storage/services/v1/info_service.proto
aruna/api/storage/services/v1/service_account_service.proto

A minor update to existing functionalities and the addition of a service account service.
1. Removed project_id from get_resource_hierarchy request, this will allow users to query a full hierarchy just by resource id without the need for a project_id
2. Added separate service for service accounts (Refers to ArunaStorage/ArunaServer#38):
Service accounts are special project bound accounts that can be managed by all project admins. They are used to authorize and manage project specific automations. 
- (1.) Breaks the old specification for the hierarchy request
- (2.) Adds an additional boolean field to ProjectPermissions that indicates if a project user associations refers to a service account.  This is only used in responses and should not break existing implementations but might break …

V0.5.0 beta.9

---

aruna/api/storage/services/v1/object_service.proto
aruna/api/storage/services/v1/objectgroup_service.proto

This is a small patch for 1.0.0.
Changelog:
- Removed `object_id` from `SetObjectPathVisibilityRequest`
- Add boolean `withRevisions` parameter to `DeleteObjectGroupRequest`

[1.0.0-rc.3] Dev 1.0.0 rc.3

---

aruna/api/internal/v1/authorize.proto
aruna/api/internal/v1/proxy.proto
aruna/api/storage/services/v1/object_service.proto

This is intended to be the last update to the API before 1.0.0. It should include no changes to the user-facing API (except the update of the OpenAPI path for `SetObjectPathVisibility`).
Full changelog:
- Removed the `object_id` part from the openapi path anotation in `SetObjectPathVisibility`
- Internal: Updated internal `authorize` method to properly handle paths and resource ids
- Internal: Added `InternalProxyNotifierService` as backwards channel to notify updates from the Dataproxy to the ArunaServer
- Internal: Added `DeleteObject` and `MoveObject` requests for the `InternalProxyService` to simplify storage location migrations and properly delete objects.

[1.0.0-rc.5] Final preparations for 1.0.0

---

aruna/api/notification/services/v1/notification_service.proto

This adds a new simplified notification API that does not need the previously used bidirectional streaming approach.
The reply string from the original NatsIO message can be used to acknowledge handled messages without keeping the original message. The API verifies the message using an HMAC.

Add new simplified event notification message

---

Cargo.lock
Cargo.toml
aruna/api/storage/models/v1/auth.proto
aruna/api/storage/models/v1/models.proto
aruna/api/storage/services/v1/object_service.proto

This PR includes some minor (non-breaking) changes for 1.0.0.
- Added `ENDPOINT_STATUS` enum
- Added new object_status `FINALIZING` -> objects need to be finalized on the storage backend before getting available
- Added `is_service_account` to user to prepare addition of service_accounts
- Added `used_at` timestamp to `api_token` indicating the last time a specific token was used.
- Added `is_session` to `api_token` to indicate a session token in preparation for ArunaWeb
Chore:
- Update tonic / prost deps to 0.9.1

[1.0.0-rc.12] Small updates for 1.0.0

---

.github/workflows/tag-creation.yaml

This adds the [ArunaStorage/java-api](https://github.com/ArunaStorage/java-api) repository to the tag creation workflow which is manually triggered after the release of a new ArunaAPI version.
The dispatch triggers the build, commit and deployment workflow in the target repository with the provided release version and description.

Add java-api repo to tag creation workflow

---

Cargo.lock
aruna/api/bundler/services/v1/bundler_service.proto
aruna/api/internal/v1/bundler.proto
tests/build.rs

This PR adds a first draft for "bundled" downloads and a "bundler" service / API described in #72.
- Add `aruna/api/bundler/services/v1/bundler_service.proto` with a publicly facing service that allows users to initiate bundles for multiple objects.
- Add internal bundler services that are used to communicate between the ArunaServer and a new bundler program.
- The Bundler exposes a small webserver that can be used to retrieve data directly from associated storage backends. It should be kept in close proximity to the data-proxy backend and will use a similar interface to make it pluggable to the same backends as the dataproxy.

[feature] Feature bundled downloads

---

aruna/api/internal/v1/authorize.proto
aruna/api/internal/v1/proxy.proto

This small update adds CORS support to the internal GetObjectLocation request and enables the dataproxy to create short-lived api tokens on behalf of the user via s3 credentials. 
With this the dataproxy can use these tokens to modify API resources via the public API directly without the need for extra internal requests.
- Added `GetTokenFromSecret` rpc to internal authorize service.
- Added optional `CorsConfiguration` to `GetObjectLocationResponse` in internal proxy notifier. (https://github.com/ArunaStorage/DataProxy/issues/29)
No breaking changes for the public API were introduced.

[feature] Cors additions / GetTokenFromSecret

---

aruna/api/storage/services/v1/object_service.proto

This fix improves the `ListObjects` API call and reduces the number of requests needed. This is addresses Issue #82.

fix: GetObjectsAsListV2Response should return ObjectWithURL

---

aruna/api/storage/services/v1/service_account_service.proto

This PR updates the service account handling. Especially the token creation process.
- Result token + s3 credentials similar to regular users
- Add project_id to create token request to allow for double checks for privilege escalations / correct project
- Remove UNFINISHED annotation 
- Rename EditServiceAccountPermissions to SetServiceAccountPermissions to make it clear that this overwrites the previous setting

[feat] Update svc account handling from dev

---

aruna/api/hooks/services/v2/hooks_service.proto
aruna/api/storage/models/v2/models.proto
aruna/api/storage/services/v2/search_service.proto

These are very basic changes needed for a minimal working example for hooks.
- `HookCallbackRequest` now contain a `secret`, `hook_id`, `object_id` and `pubkey_serial` field.
- `EndpointHostType` are changed to `GRPC` and `S3` fields.

feat: Needed changes for a minimal Hooks working example

---

aruna/api/dataproxy/services/v2/bundler_service.proto
aruna/api/storage/models/v2/models.proto
aruna/api/storage/services/v2/user_service.proto

This PR adds the ability to add more than one external identity provider.
- Remove external_id from user to user_attributes 
- Created an OIDCMapping message that combines an external id with a corresponding oidc provider
- Added functions to Add or remove other OIDC provider to an existing account#
- (typo) rename repeated `resource_id` to `resource_ids` in bundler

[2.0.0 beta.8] Multi-oidc support

---

aruna/api/storage/models/v2/models.proto

This fixes an inheritance issue emerging from explicitly stating IDs in `variant` for `DataEndpoint`.
- Updating relations no longer requires updating every object with a new Origin Id inside `variant`.
- Only one status for endpoint and resource can be set

fix: Replication status messages in objects

---

Cargo.lock
Cargo.toml
aruna/api/dataproxy/services/v2/bundler_service.proto
aruna/api/dataproxy/services/v2/dataproxy_service.proto
aruna/api/storage/models/v2/models.proto
aruna/api/storage/services/v2/collection_service.proto
aruna/api/storage/services/v2/dataset_service.proto
aruna/api/storage/services/v2/object_service.proto
aruna/api/storage/services/v2/project_service.proto
aruna/api/storage/services/v2/rules_service.proto
aruna/api/storage/services/v2/service_account_service.proto
aruna/api/storage/services/v2/user_service.proto
aruna/api/storage/services/v2/workspace_service.proto

Adds main features needed for a final release. This includes changes needed for the data proxy overhaul, server side rules and missing fields for objects and users.
- Splitting `GetS3Credentials` into `Get/Create/DeleteS3Credentials` on server and proxy side.
- Adding data proxy file ingestion
- `PullReplication` rework to efficiently use pithos file format as a replication protocol
- First and last name fields for users
- Data proxy specific attributes for users
- A pubkey field for users
- Author & title fields for objects
- Rules & rule bindings for resources including workspaces
- Update requests for added fields
- A `SetObjectHashes` function that either adds new hashes or compares hashes
- A rule service to create and update rules for resources

V2.0.0 beta.12

---

aruna/api/dataproxy/services/v2/dataproxy_service.proto

This adds new messages for the data replication protocol, addressing stale channel connections and syncing not finalized objects

fix: Added handshake and skip messages for data replication

---

aruna/api/storage/models/v2/models.proto
aruna/api/storage/services/v2/info_service.proto

This pull request introduces enhancements to the API for public announcements within the `StorageStatusService` by extending the `Announcement` message with the following fields:
* `announcement_type`: A non-exhaustive type to differentiate announcements
* `title`: A title for the announcement
* `teaser`: A short summary of the announcement
* `created_by`: An id or display name of the original author
* `modified_by`: An id or display name of the last person that modified the announcement
* `modified_at`: Timestamp of the last modification
In addition, the `StorageStatusService` gets extended by the following 
* Extended endpoint `GetAnnouncements` with an optional id filter
* New endpoint `GetAnnouncement`, which enables the specific query of an announcement based on its id
* New endpoint …

Extend public announcements

---

aruna/api/storage/services/v2/info_service.proto

This extends the `Announcement` message by adding an additional field `image_url`. This field will provide the URL of a preview image, allowing announcements display to include visual content for better engagement and context. The change aims to improve the user experience by providing a richer, more informative announcement display.

Add preview image url field to Announcement

---

aruna/api/storage/services/v2/object_service.proto

This pull request introduces an extension to the URL creation endpoint by adding the `upload_id` field to both the `GetUploadURLRequest` and `GetUploadURLResponse`. This extension addresses the issue that an upload id generated for a multipart upload has to be provided for the creation of the following upload URLs that are used for the remaining parts.

Add upload_id to to upload url requests

---

aruna/api/storage/services/v2/object_service.proto

This pull request introduces an extension to the `FinishObjectStagingRequest` by adding the `upload_id` field. This extension addresses the issue that an upload id generated for a multipart upload needs to be provided if a user wants to manually signal the completion of a multipart upload to the Aruna Server.

Add upload_id to FinishObjectStagingRequest
